apiVersion: v1
kind: Service
metadata:
  name: {{ .loadGeneratorServiceName }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .loadGeneratorName }}
spec:
  selector:
    app: {{ .loadGeneratorName }}
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
