apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: app-demo-standalone
  labels:
    app: demo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: backend
          image: kind.local/demo-app-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: APP_NAME
              value: movie-night-backend
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  namespace: app-demo-standalone
spec:
  selector:
    app: demo-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
