apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-frontend-config
  namespace: app-demo-standalone
data:
  config.js: |
    window.__BACKEND_URL__ = 'http://localhost:8081';

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: app-demo-standalone
  labels:
    app: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: frontend
          image: kind.local/demo-app-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config
          configMap:
            name: demo-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: app-demo-standalone
spec:
  selector:
    app: demo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
